import React from 'react';
import './contact-view.css';

export const SendingMessage = () => {
    return (
        <div className="form-container">
            {/* Sending spinner * [ldio] generated by https://loading.io */}
            <div
                class="loadingio-spinner-spinner-64digdqy0vp"
                style={{ backgroundColor: 'transparent' }}
            >
                <div class="ldio-alennszij0f">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            <p style={{ position: 'absolute', color: '#fff', margin: 0 }}>
                Sending...
            </p>
        </div>
    );
};
